CREATE TABLE [dbo].[MealTable]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [Name] NCHAR(10) NULL, 
    [Drink Alternate] NCHAR(10) NULL, 
    [Category] NCHAR(10) NULL, 
    [Area] NCHAR(10) NULL, 
    [Instructions] TEXT NULL, 
    [ThumbNail] TEXT NULL, 
    [Youtube] TEXT NULL, 
    [Ingred1] TEXT NULL, 
    [Ingred2] TEXT NULL, 
    [Ingred3] NCHAR(10) NULL, 
    [Ingred4] NCHAR(10) NULL, 
    [Ingred5] NCHAR(10) NULL,
    [Ingred6] NCHAR(10) NULL,
    [Ingred7] NCHAR(10) NULL,
    [Ingred8] NCHAR(10) NULL,
    [Ingred9] NCHAR(10) NULL,
    [Ingred10] NCHAR(10) NULL,
    [Ingred11] NCHAR(10) NULL,
    [Ingred12] NCHAR(10) NULL,
    [Ingred13] NCHAR(10) NULL,
    [Ingred14] NCHAR(10) NULL,
    [Ingred15] NCHAR(10) NULL,
    [Ingred16] NCHAR(10) NULL,
    [Ingred17] NCHAR(10) NULL,
    [Ingred18] NCHAR(10) NULL,
    [Ingred19] NCHAR(10) NULL,
    [Ingred20] NCHAR(10) NULL, 
    [Measure1] NCHAR(10) NULL,
    [Measure2] NCHAR(10) NULL,
    [Measure3] NCHAR(10) NULL,
    [Measure4] NCHAR(10) NULL,
    [Measure5] NCHAR(10) NULL,
    [Measure6] NCHAR(10) NULL,
    [Measure7] NCHAR(10) NULL,
    [Measure8] NCHAR(10) NULL,
    [Measure9] NCHAR(10) NULL,
    [Measure10] NCHAR(10) NULL,
    [Measure11] NCHAR(10) NULL,
    [Measure12] NCHAR(10) NULL,
    [Measure13] NCHAR(10) NULL,
    [Measure14] NCHAR(10) NULL,
    [Measure15] NCHAR(10) NULL,
    [Measure16] NCHAR(10) NULL,
    [Measure17] NCHAR(10) NULL,
    [Measure18] NCHAR(10) NULL,
    [Measure19] NCHAR(10) NULL,
    [Measure20] NCHAR(10) NULL, 
    [Source] NVARCHAR(50) NULL, 
    [ImageSource] NVARCHAR(50) NULL, 
    [CreativeCommonsConfirmed] NVARCHAR(50) NULL, 
    [dateModified] NCHAR(10) NULL,

)
